### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by powermarcel10** [iamdevnl/plugin.video.nlziet#3]
Hi, I found this addon, really nice that you are working on a nlziet addon for kodi! However, the addon is not working here.. I'm able to login and see the channels, but when I try to start a stream, nothing happend.. Should it stil work?

**Comment by blokkie58** [comment]
Yes, found this addon too! Sadly it doesn’t stream at all..... I think that this addon has a lot of potential, so I’m glad to help in testing when needed! And yes i have an NL ZIET account, please respond!!

**Comment by iamdevnl** [comment]
Hi,

Are you using the latest version of Kodi? What OS are you running?
This addon currently runs in Kodi 18.6 on my MacBook (MacOS 10.15)  and Raspberry Pi (4b).

**Comment by powermarcel10** [comment]
Aaaaah allright. Windows indeed. Thanks for the reply!

**Comment by iamdevnl** [comment]
Hi,

The problem should be solved!
